name = "BootstrapBill"
uuid = "8873c484-bbb2-4c18-9d57-e1b79bc0a19a"
authors = ["Raye Kimmerer <raye@rayegun.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
